name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build --if-present

  build-and-push-docker-image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.G_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            subrataparamanick1234/test-react-pipeline:${{ github.sha }}
            ghcr.io/subrataparamanick1234/test-react-pipeline:${{ github.sha }}

  update-manifest-stage:
    name: Update Manifest Repo
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: subrataparamanick1234/pineline-main-repo
          ref: master
          token: ${{ secrets.G_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "subrataparamanick1234@gmail.com"
          git config --global user.name "subrataparamanick1234"

      - name: Update deployment image tag
        run: |
          sed -i "s#${{ github.actor }}.*#${{ github.actor }}/test-react-pipeline:${{ github.sha }}#g" deployment.yaml
          git add deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin main
